spring:
  application:
    name: moyeorock

  datasource:
    url: jdbc:mysql://localhost:3306/moyeorock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    com.moyeorock: debug
    org.hibernate.SQL: debug